### ISSUE TITLE
Feature request: Hook for logging requests / reponses

### ISSUE THREAD

**Issue by fwc** [enowars/enochecker3#37] opened 2023-06-17 11:51 UTC
Httpx allows for adding [event hooks](https://www.python-httpx.org/advanced/#event-hooks) that make it easy to log requests/responses like the following:

```python
def log_request(request):
    print(f"Request event hook: {request.method} {request.url} - Waiting for response")

def log_response(response):
    request = response.request
    print(f"Response event hook: {request.method} {request.url} - Status {response.status_code}")

client = httpx.Client(event_hooks={'request': [log_request], 'response': [log_response]})
```

I'd suggest to enable rudimentary logging like in the snippet and/or to create the possibility for checker writes to register their own hooks, since they should know what to expect and how to log it, e.g. logging exif metadata for an incoming image.

**Comment by sinitax** [comment] 2023-10-02 22:03
There is currently no way to pass additional arguments (such as a hooks list) to the default provided dependency injectors. This is intended, as passing such parameters via the checker method signature would make the code unreadable.

Instead, to make use of additional httpx options, you should create a separate named dependency injector which you can invoke by [naming the function parameters appropriately](https://github.com/enowars/enochecker3/blob/282eaacda2f222aedbd46baeadba8c7e8d986ecc/enochecker3/enochecker.py#L235).

Here is a mock example:

```python
# ...

checker = Enochecker("ExampleService", 1337)

myhooks = # ...

def custom_http_client(self, task: BaseCheckerTaskMessage) -> httpx.Client:
    return httpx.Client(base_url=f"http://{task.address}:{self.service_port}", verify=False, event_hooks=my_hooks)

checker.register_named_dependency("custom")(custom_http_client)

@checker.putflag(0)
async def putflag_test(task: PutflagCheckerTaskMessage, custom_client: httpx.Client, db: ChainDb) -> None:
    # ...

# ...

```

**Comment by sinitax** [comment] 2023-10-02 22:04
Closing this for now, since the issue is quite old and im guessing you have worked around the issue by now. Feel free to reopen is necessary.

**Closed by sinitax** 2023-10-02 22:04 UTC
